allowMergeCommits: true
# Always validate the PR title AND all the commits
titleAndCommits: true
types:
    - feat
    - fix
    - style
    - build
    - ci
    - revert
scopes:
    - api
    - adr
    - legacy
    - examples
    - microservices
    - ref
    - walkthru
