site_name: EdgeX Foundry Documentation
docs_dir: docs_src
site_dir: docs/3.1
site_description: 'Documentation for use of EdgeX Foundry'
site_author: 'Michael Johanson'
site_url: 'https://docs.edgexfoundry.org/3.1'
repo_url: 'https://github.com/edgexfoundry/edgex-go'
repo_name: 'edgex/edgex-go'
copyright: 'Copyright &copy; 2023 EdgeX Foundry'
strict: false   # mkdocs-materials will prevent running on 0.0.0.0 otherwise (or have custom image)
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: info
    unrecognized_links: ignore
theme:
  name: 'material'
  logo: 'assets/logo_edgex_white.png'
  favicon: 'assets/logo_edgex.png'
  features:
    - navigation.tabs  # changed with version 6 of mkdocs-materials
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: custom 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home:
    - Overview: index.md
    - about.md
    - Getting Started: 
      - Guides: getting-started/index.md
      - getting-started/quick-start/index.md
      - getting-started/Ch-GettingStartedUsers.md
      - getting-started/Ch-GettingStartedDockerUsers.md
      - getting-started/Ch-GettingStartedSnapUsers.md
      - getting-started/tools/Ch-GUI.md
    - Developer:
        - getting-started/Ch-GettingStartedDevelopers.md
        - getting-started/Ch-GettingStartedGoDevelopers.md
        - getting-started/Ch-GettingStartedCDevelopers.md
        - getting-started/Ch-GettingStartedHybrid.md
        - Native Build and Run Guides:
            - getting-started/native/Ch-BuildRunNative.md
            - getting-started/native/Ch-BuildRunOnLinuxDistro.md
            - getting-started/native/Ch-BuildRunOnArm32.md
            - getting-started/native/Ch-BuildRunOnWindows.md
        - Application Functions SDK: microservices/application/sdk/Purpose.md
        - Device Services:
            - getting-started/Ch-GettingStartedSDK.md
            - getting-started/Ch-GettingStartedSDK-C.md
            - getting-started/Ch-GettingStartedSDK-Go.md
        - getting-started/Ch-GettingStartedUsersNexus.md
        - getting-started/Ch-GettingStartedDTOValidation.md
    - Services:
      - Core: 
        - microservices/core/Ch-CoreServices.md
        - Core Data:
            - Purpose: microservices/core/data/Purpose.md
            - Getting Started: microservices/core/data/GettingStarted.md
            - Configuration: microservices/core/data/Configuration.md
            - API Reference: microservices/core/data/ApiReference.md
            - Source Code: microservices/core/data/SourceCode.md
            - Additional Details:
              - Events and Readings: microservices/core/data/details/EventsAndReadings.md
        - microservices/core/metadata/Ch-Metadata.md
        - microservices/core/command/Ch-Command.md
        - microservices/core/database/Ch-Redis.md
      - Supporting: 
        - microservices/support/Ch-SupportingServices.md
        - microservices/support/notifications/Ch-AlertsNotifications.md
        - microservices/support/scheduler/Ch-Scheduler.md
        - microservices/support/eKuiper/Ch-eKuiper.md
      - Device:
        - Overview: microservices/device/Ch-DeviceServices.md
        - microservices/device/profile/Ch-DeviceProfile.md
        - Device Service SDK: microservices/device/sdk/Ch-DeviceSDK.md
        - Device SDK API: microservices/device/sdk/SDK-Go-API.md
        - Device Services:
          - Available Services: microservices/device/services/Ch-DeviceServiceList.md
          - Device BacNet: microservices/device/services/device-bacnet.md
          - Device COAP: microservices/device/services/device-coap.md
          - Device GPIO: microservices/device/services/device-gpio.md
          - Device ModBus: microservices/device/services/device-modbus.md
          - Device MQTT: microservices/device/services/device-mqtt.md
          - Device Onvif Camera:
              - microservices/device/services/device-onvif-camera/General.md
              - microservices/device/services/device-onvif-camera/swagger.md
              - Walkthrough:
                  - microservices/device/services/device-onvif-camera/Walkthrough/setup.md
                  - microservices/device/services/device-onvif-camera/Walkthrough/deployment.md
                  - microservices/device/services/device-onvif-camera/Walkthrough/general-usage.md
                  - microservices/device/services/device-onvif-camera/Walkthrough/custom-build.md
              - Supplementary Information:
                  - ONVIF Protocol:
                      - microservices/device/services/device-onvif-camera/supplementary-info/ONVIF-protocol.md
                      - microservices/device/services/device-onvif-camera/supplementary-info/onvif-user-authentication.md
                  - Features:
                      - microservices/device/services/device-onvif-camera/supplementary-info/custom-metadata-feature.md
                      - microservices/device/services/device-onvif-camera/supplementary-info/friendlyname-mac.md
                      - microservices/device/services/device-onvif-camera/supplementary-info/device-status.md
                      - microservices/device/services/device-onvif-camera/supplementary-info/auto-discovery.md
                      - microservices/device/services/device-onvif-camera/supplementary-info/credentials.md
                      - microservices/device/services/device-onvif-camera/supplementary-info/reboot-needed.md
                  - API Reference:
                      - microservices/device/services/device-onvif-camera/supplementary-info/api-analytic-support.md
                      - microservices/device/services/device-onvif-camera/supplementary-info/api-event-handling.md
                      - microservices/device/services/device-onvif-camera/supplementary-info/api-usage-user-handling.md
                  - Utility:
                      - microservices/device/services/device-onvif-camera/supplementary-info/test-with-postman.md
                      - microservices/device/services/device-onvif-camera/supplementary-info/utility-scripts.md
                  - Miscellaneous:
                      - microservices/device/services/device-onvif-camera/supplementary-info/control-plane-events.md
                      - microservices/device/services/device-onvif-camera/supplementary-info/getting-started-with-docker-security.md
                      - microservices/device/services/device-onvif-camera/supplementary-info/ws-discovery.md
                      - microservices/device/services/device-onvif-camera/supplementary-info/onvif-footnotes.md
          - Device REST: microservices/device/services/device-rest.md
          - Device RFID LLRP: microservices/device/services/device-rfid-llrp.md
          - Device SNMP: microservices/device/services/device-snmp.md
          - Device UART: microservices/device/services/device-uart.md
          - Device USB Camera:
              - microservices/device/services/device-usb-camera/General.md
              - Walkthrough:
                  - microservices/device/services/device-usb-camera/walkthrough/setup.md
                  - microservices/device/services/device-usb-camera/walkthrough/deployment.md
                  - microservices/device/services/device-usb-camera/walkthrough/general-usage.md
                  - microservices/device/services/device-usb-camera/walkthrough/custom-build.md
              - Supplementary Information:
                  - microservices/device/services/device-usb-camera/supplementary-info/USB-protocol.md
                  - microservices/device/services/device-usb-camera/supplementary-info/discovery.md
                  - microservices/device/services/device-usb-camera/supplementary-info/advanced-options.md
          - Device Virtual: microservices/device/services/device-virtual/Ch-VirtualDevice.md
          - Remote Deployment:
              - Non-Secure Mode: microservices/device/remote/Ch-RemoteNonSecure.md
              - Secure Mode: microservices/device/remote/Ch-RemoteSecure.md
        - V3 Migration: microservices/device/V3Migration.md
      - Application:
        - Application Services: microservices/application/ApplicationServices.md
        - Getting Started: microservices/application/GettingStarted.md
        - Configuration: microservices/application/Configuration.md
        - API Reference: microservices/application/ApiReference.md
        - App Functions SDK:
            - Purpose: microservices/application/sdk/Purpose.md
            - Getting Started: microservices/application/sdk/GettingStarted.md
            - APIs:
                - Application Service: microservices/application/sdk/api/ApplicationServiceAPI.md
                - App Function Context: microservices/application/sdk/api/AppFunctionContextAPI.md
                - Pipeline Functions: microservices/application/sdk/api/BuiltInPipelineFunctions.md
            - Source Code: microservices/application/sdk/SourceCode.md
            - Additional Details:
                - Triggers: microservices/application/sdk/details/Triggers.md
                - Custom Configuration: microservices/application/sdk/details/CustomConfiguration.md
                - Advanced Topics: microservices/application/sdk/details/AdvancedTopics.md
        - Services:
            - App Service Configurable:
                - Purpose: microservices/application/services/AppServiceConfigurable/Purpose.md
                - Getting Started: microservices/application/services/AppServiceConfigurable/GettingStarted.md
                - Configuration: microservices/application/services/AppServiceConfigurable/Configuration.md
                - API Reference: microservices/application/services/AppServiceConfigurable/ApiReference.md
                - Source Code: microservices/application/services/AppServiceConfigurable/SourceCode.md
                - Additional Details:
                  - Pipeline Per Topics: microservices/application/services/AppServiceConfigurable/details/PipelinePerTopics.md
                  - Available Pipeline Functions: microservices/application/services/AppServiceConfigurable/details/AvailablePipelineFunctions.md
                  - Available Profiles: microservices/application/services/AppServiceConfigurable/details/Profiles.md
                  - Target Type: microservices/application/services/AppServiceConfigurable/details/TargetType.md
            - App RFID LLRP Inventory: microservices/application/services/AppLLRPInventory.md
            - App Record & Replay :
                - Purpose: microservices/application/services/AppRecordReplay/Purpose.md
                - Getting Started: microservices/application/services/AppRecordReplay/GettingStarted.md
                - Configuration: microservices/application/services/AppRecordReplay/Configuration.md
                - API Reference: microservices/application/services/AppRecordReplay/ApiReference.md
                - Source Code: microservices/application/services/AppRecordReplay/SourceCode.md
        - V3 Migration: microservices/application/V3Migration.md
      - Configuration & Registry:
        - microservices/configuration/ConfigurationAndRegistry.md
        - microservices/configuration/CommonConfiguration.md
        - microservices/configuration/CommonCommandLineOptions.md
        - microservices/configuration/CommonEnvironmentVariables.md
        - V3 Migration: microservices/configuration/V3MigrationCommonConfig.md
      - microservices/general/index.md
      - microservices/general/messagebus.md
    - Security:
      - Security Services: security/Ch-Security.md
      - security/Ch-SecretStore.md
      - security/Ch-Authenticating.md
      - security/Ch-SecretProviderApi.md
      - security/Ch-APIGateway.md
      - security/Ch-Secure-MessageBus.md
      - security/Ch-Configuring-Add-On-Services.md
      - security/Ch-Secure-Consul.md
      - security/Ch-SecurityIssues.md
      - security/secrets-config.md
      - security/secrets-config-proxy.md
      - security/SeedingServiceSecrets.md
      - security/Ch-CORS-Settings.md
      - security/Ch-DelayedStartServices.md
      - security/Ch-RemoteDeviceServices.md
      - V3 Migration: security/V3Migration.md
      - Threat Models:
        - threat-models/secret-store/README.md
        - threat-models/stride-model/EdgeX-STRIDE.md
        - threat-models/stride-model/EdgeXFoundryThreatReportV2.2.md
    - Migration:
      - V3.0 Migration:
        - General Migration: V3TopLevelMigration.md
        - Security Migration: security/V3Migration.md
        - Configuration Migration: microservices/configuration/V3MigrationCommonConfig.md
        - Device Service Migration: microservices/device/V3Migration.md
        - Application Service Migration: microservices/application/V3Migration.md
    - Tutorials:
      - examples/Ch-ExamplesVirtualDeviceService.md
      - examples/Ch-ExamplesSendingAndConsumingBinary.md
      - examples/Ch-CommandingDeviceThroughRulesEngine.md
      - examples/Ch-ExamplesModbusdatatypeconversion.md
      - examples/Ch-OSImageWithEdgeX.md
      - examples/Ch-ExamplesDataandRetention.md
      - Adding a Device:
        - examples/Ch-ExamplesAddingModbusDevice.md
        - examples/Ch-ExamplesAddingSNMPDevice.md
        - examples/Ch-ExamplesAddingMQTTDevice.md
      - Walkthrough:
        - walk-through/Ch-Walkthrough.md
        - walk-through/Ch-WalkthroughSetup.md
        - walk-through/Ch-WalkthroughUseCase.md
        - walk-through/Ch-WalkthroughDeviceProfile.md
        - walk-through/Ch-WalkthroughDeviceService.md
        - walk-through/Ch-WalkthroughProvision.md
        - walk-through/Ch-WalkthroughCommands.md
        - walk-through/Ch-WalkthroughReading.md
        - walk-through/Ch-WalkthroughExporting.md
    - Examples:
      - Code Examples: examples/index.md
      - App Service Examples:
        - examples/AppServiceExamples.md
        - examples/app-service-examples/camera-management/Ch-CameraManagement.md
    - APIs: 
      - api/Ch-APIIntroduction.md
      - api/core/Ch-APICoreCommand.md
      - Core Data: microservices/core/data/ApiReference.md
      - api/core/Ch-APICoreMetadata.md
      - api/core/Ch-APICoreConfigurationAndRegistry.md
      - api/support/Ch-APISupportNotifications.md
      - api/support/Ch-APISupportScheduler.md
      - api/devices/Ch-APIDeviceSDK.md
      - App Services: microservices/application/ApiReference.md
      - api/applications/Ch-APIRulesEngine.md  
  - Reference:
    - general/Definitions.md
    - general/PlatformRequirements.md
    - general/ServicePorts.md
    - general/ContainerNames.md
    - general/ServiceConfiguration.md
    - general/EdgeX_CN.md
  - Use Case & Design:
    - Process: design/Process.md
    - Documents: design/TOC.md
    - Legacy:
      - Designs: design/legacy-design/README.md
      - Requirements: design/legacy-requirements/README.md
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
  # - mdx_truly_sane_lists
extra:
  version:
    provider: mike
  # - make edgexversion the latest version for repository tree references
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/edgexfoundry'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/edgexfoundry'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/edgexfoundry'
  analytics:
    provider: google
    property: G-38531ZZHBN
extra_css:
- assets/stylesheets/version-select.css
- assets/stylesheets/branding.css
- assets/stylesheets/edgey.css
- assets/stylesheets/newexample.css
- assets/stylesheets/extra.css
plugins:
  - search
  - swagger-ui-tag
  - macros:
      include_yaml:
        - template_macros.yaml
      on_error_fail: true
  - htmlproofer:
      enabled: !ENV [ENABLED_HTMLPROOFER, false]
      raise_error: true
      raise_error_excludes:
        404: ['https://support.google.com/accounts/answer/185833?hl=en',
              'https://support.google.com/accounts/answer/6010255?hl=en']
        429: ['*']
        -1: ['https://www.rfc-editor.org/rfc/rfc7519',
             'https://tools.ietf.org/html/rfc5869','https://docs.iotaap.io/docs-rest/']
        500: [https://packages.ubuntu.com/bionic/build-essential]
