site_name: EdgeX Foundry Documentation
site_description: 'Documentation for use of EdgeX Foundry'
site_author: 'Jim White'
site_url: 'https://github.com/edgexfoundry/edgex-docs'
repo_url: 'https://github.com/edgexfoundry/edgex-go'
repo_name: 'edgex/edgex-go'
copyright: 'Copyright &copy; 2023 EdgeX Foundry'
docs_dir: docs_src
site_dir: docs/3.1
strict: false   # mkdocs-materials will prevent running on 0.0.0.0 otherwise (or have custom image)
extra:
  version:
    provider: mike
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: info
    unrecognized_links: ignore
theme:
  name: 'material'
  logo: 'assets/logo_edgex_white.png'
  favicon: 'assets/logo_edgex.png'
  features:
    - navigation.tabs  # changed with version 6 of mkdocs-materials
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: custom 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home:
    - Overview: index.md
    - about.md
    - Getting Started: 
      - Guides: getting-started/index.md
      - getting-started/quick-start/index.md
      - getting-started/Ch-GettingStartedUsers.md
      - getting-started/Ch-GettingStartedDockerUsers.md
      - getting-started/Ch-GettingStartedSnapUsers.md
      - getting-started/tools/Ch-GUI.md
    - Services:
      - Core: 
        - microservices/core/Ch-CoreServices.md
        - microservices/core/data/Ch-CoreData.md
        - microservices/core/metadata/Ch-Metadata.md
        - microservices/core/command/Ch-Command.md
        - microservices/core/database/Ch-Redis.md
      - Supporting: 
        - microservices/support/Ch-SupportingServices.md
        - microservices/support/notifications/Ch-AlertsNotifications.md
        - microservices/support/scheduler/Ch-Scheduler.md
        - microservices/support/eKuiper/Ch-eKuiper.md
      - Device: 
        - microservices/device/Ch-DeviceServices.md
        - microservices/device/profile/Ch-DeviceProfile.md
        - Device Service SDK: microservices/device/sdk/Ch-DeviceSDK.md
        - Device SDK API: microservices/device/sdk/SDK-Go-API.md
        - Supported Device Services: 
          - microservices/device/Ch-DeviceServiceList.md
          - Device Onvif Camera: 
            - microservices/device/supported/device-onvif-camera/General.md
            - microservices/device/supported/device-onvif-camera/swagger.md
            - Walkthrough:
              - microservices/device/supported/device-onvif-camera/Walkthrough/setup.md
              - microservices/device/supported/device-onvif-camera/Walkthrough/deployment.md
              - microservices/device/supported/device-onvif-camera/Walkthrough/general-usage.md
              - microservices/device/supported/device-onvif-camera/Walkthrough/custom-build.md
            - Supplementary Information:
              - ONVIF Protocol:
                - microservices/device/supported/device-onvif-camera/supplementary-info/ONVIF-protocol.md
                - microservices/device/supported/device-onvif-camera/supplementary-info/onvif-user-authentication.md
              - Features: 
                - microservices/device/supported/device-onvif-camera/supplementary-info/custom-metadata-feature.md
                - microservices/device/supported/device-onvif-camera/supplementary-info/friendlyname-mac.md
                - microservices/device/supported/device-onvif-camera/supplementary-info/device-status.md
                - microservices/device/supported/device-onvif-camera/supplementary-info/auto-discovery.md
                - microservices/device/supported/device-onvif-camera/supplementary-info/credentials.md 
                - microservices/device/supported/device-onvif-camera/supplementary-info/reboot-needed.md
              - API Reference:
                - microservices/device/supported/device-onvif-camera/supplementary-info/api-analytic-support.md
                - microservices/device/supported/device-onvif-camera/supplementary-info/api-event-handling.md
                - microservices/device/supported/device-onvif-camera/supplementary-info/api-usage-user-handling.md
              - Utility:
                - microservices/device/supported/device-onvif-camera/supplementary-info/test-with-postman.md
                - microservices/device/supported/device-onvif-camera/supplementary-info/utility-scripts.md
              - Miscellaneous:
                - microservices/device/supported/device-onvif-camera/supplementary-info/control-plane-events.md
                - microservices/device/supported/device-onvif-camera/supplementary-info/getting-started-with-docker-security.md
                - microservices/device/supported/device-onvif-camera/supplementary-info/ws-discovery.md
                - microservices/device/supported/device-onvif-camera/supplementary-info/onvif-footnotes.md
          - Device USB Camera:
              - microservices/device/supported/device-usb-camera/General.md
              - Walkthrough:
                - microservices/device/supported/device-usb-camera/walkthrough/setup.md
                - microservices/device/supported/device-usb-camera/walkthrough/deployment.md
                - microservices/device/supported/device-usb-camera/walkthrough/general-usage.md
                - microservices/device/supported/device-usb-camera/walkthrough/custom-build.md
              - Supplementary Information:
                - microservices/device/supported/device-usb-camera/supplementary-info/discovery.md
                - microservices/device/supported/device-usb-camera/supplementary-info/advanced-options.md   
          - Device Virtual: microservices/device/supported/device-virtual/Ch-VirtualDevice.md
        - V3 Migration: microservices/device/V3Migration.md
      - Application:
        - microservices/application/ApplicationServices.md
        - Getting Started: microservices/application/GettingStarted.md
        - Triggers: microservices/application/Triggers.md
        - Application Functions SDK:
            - App Functions ADK: microservices/application/ApplicationFunctionsSDK.md
            - microservices/application/ApplicationServiceAPI.md
            - microservices/application/AppFunctionContextAPI.md
            - microservices/application/ErrorHandling.md
            - microservices/application/BuiltIn.md
            - microservices/application/AdvancedTopics.md
        - microservices/application/AppServiceConfigurable.md
        - microservices/application/GeneralAppServiceConfig.md
        - V3 Migration: microservices/application/V3Migration.md
      - SDKs:
        - microservices/application/ApplicationFunctionsSDK.md
        - microservices/device/sdk/Ch-DeviceSDK.md
      - Configuration & Registry:
        - microservices/configuration/ConfigurationAndRegistry.md
        - microservices/configuration/CommonConfiguration.md
        - microservices/configuration/CommonCommandLineOptions.md
        - microservices/configuration/CommonEnvironmentVariables.md
        - V3 Migration: microservices/configuration/V3MigrationCommonConfig.md
      - microservices/general/index.md
      - microservices/general/messagebus.md
    - Security:
      - Security Services: security/Ch-Security.md
      - security/Ch-SecretStore.md
      - security/Ch-Authenticating.md
      - security/Ch-SecretProviderApi.md
      - security/Ch-APIGateway.md
      - security/Ch-Secure-MessageBus.md
      - security/Ch-Configuring-Add-On-Services.md
      - security/Ch-Secure-Consul.md
      - security/Ch-SecurityIssues.md
      - security/secrets-config.md
      - security/secrets-config-proxy.md
      - security/SeedingServiceSecrets.md
      - security/Ch-CORS-Settings.md
      - security/Ch-DelayedStartServices.md
      - security/Ch-RemoteDeviceServices.md
      - V3 Migration: security/V3Migration.md
      - Threat Models:
        - threat-models/secret-store/README.md
        - threat-models/stride-model/EdgeX-STRIDE.md
        - threat-models/stride-model/EdgeXFoundryThreatReportV2.2.md
    - Migration:
      - V3.0 Migration:
        - General Migration: V3TopLevelMigration.md
        - Security Migration: security/V3Migration.md
        - Configuration Migration: microservices/configuration/V3MigrationCommonConfig.md
        - Device Service Migration: microservices/device/V3Migration.md
        - Application Service Migration: microservices/application/V3Migration.md
    - Developer:
      - getting-started/Ch-GettingStartedDevelopers.md
      - getting-started/Ch-GettingStartedGoDevelopers.md
      - getting-started/Ch-GettingStartedCDevelopers.md
      - getting-started/Ch-GettingStartedHybrid.md
      - Native Build and Run Guides:
        - getting-started/native/Ch-BuildRunNative.md
        - getting-started/native/Ch-BuildRunOnLinuxDistro.md
        - getting-started/native/Ch-BuildRunOnArm32.md
        - getting-started/native/Ch-BuildRunOnWindows.md
      - Application Functions SDK: getting-started/ApplicationFunctionsSDK.md
      - Device Services:
        - getting-started/Ch-GettingStartedSDK.md
        - getting-started/Ch-GettingStartedSDK-C.md
        - getting-started/Ch-GettingStartedSDK-Go.md
      - getting-started/Ch-GettingStartedUsersNexus.md
      - getting-started/Ch-GettingStartedDTOValidation.md
    - Tutorials:
      - examples/Ch-ExamplesVirtualDeviceService.md
      - examples/Ch-ExamplesSendingAndConsumingBinary.md
      - examples/Ch-CommandingDeviceThroughRulesEngine.md
      - examples/Ch-ExamplesModbusdatatypeconversion.md
      - examples/Ch-OSImageWithEdgeX.md
      - Adding a Device:
        - examples/Ch-ExamplesAddingModbusDevice.md
        - examples/Ch-ExamplesAddingSNMPDevice.md
        - examples/Ch-ExamplesAddingMQTTDevice.md
      - Walkthrough:
        - walk-through/Ch-Walkthrough.md
        - walk-through/Ch-WalkthroughSetup.md
        - walk-through/Ch-WalkthroughUseCase.md
        - walk-through/Ch-WalkthroughDeviceProfile.md
        - walk-through/Ch-WalkthroughDeviceService.md
        - walk-through/Ch-WalkthroughProvision.md
        - walk-through/Ch-WalkthroughCommands.md
        - walk-through/Ch-WalkthroughReading.md
        - walk-through/Ch-WalkthroughExporting.md
    - Examples:
      - Code Examples: examples/index.md
      - App Service Examples:
        - examples/AppServiceExamples.md
        - examples/app-service-examples/camera-management/Ch-CameraManagement.md
    - APIs: 
      - api/Ch-APIIntroduction.md
      - api/core/Ch-APICoreCommand.md
      - api/core/Ch-APICoreData.md
      - api/core/Ch-APICoreMetadata.md
      - api/core/Ch-APICoreConfigurationAndRegistry.md
      - api/support/Ch-APISupportNotifications.md
      - api/support/Ch-APISupportScheduler.md
      - api/devices/Ch-APIDeviceSDK.md
      - api/applications/Ch-APIAppFunctionsSDK.md
      - api/applications/Ch-APIRulesEngine.md  
  - Reference:
    - general/Definitions.md
    - general/PlatformRequirements.md
    - general/ServicePorts.md
    - general/ContainerNames.md
    - general/ServiceConfiguration.md
    - general/EdgeX_CN.md
  - Use Case & Design:
    - Process: design/Process.md
    - Documents: design/TOC.md
    - Legacy:
      - Designs: design/legacy-design/README.md
      - Requirements: design/legacy-requirements/README.md
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
  # - mdx_truly_sane_lists
extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/edgexfoundry'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/edgexfoundry'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/edgexfoundry'
  analytics:
    provider: google
    property: G-38531ZZHBN
extra_css:
- assets/stylesheets/version-select.css
- assets/stylesheets/branding.css
- assets/stylesheets/edgey.css
- assets/stylesheets/newexample.css
- assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/version-select.js
plugins:
  - search
  - swagger-ui-tag
  - mermaid2
  - macros:
      include_yaml:
        - template_macros.yaml
      on_error_fail: true
  - htmlproofer:
      enabled: !ENV [ENABLED_HTMLPROOFER, false]
      raise_error: true
      raise_error_excludes:
        404: ['https://support.google.com/accounts/answer/185833?hl=en',
              'https://support.google.com/accounts/answer/6010255?hl=en']
        429: ['*']
        -1: ['https://www.rfc-editor.org/rfc/rfc7519',
             'https://tools.ietf.org/html/rfc5869','https://docs.iotaap.io/docs-rest/']
        500: [https://packages.ubuntu.com/bionic/build-essential]
